### ISSUE TITLE
System "gadgets" not found

### ISSUE THREAD

**Issue by lloydhuang** [BnMcGn/ps-gadgets#1]
Git clone ps-gadgets into ~/quicklisp/local-projects/

try below command.
(ql:quickload :ps-gadgets)

Get ERROR MESSAGE
> System "gadgets" not found
>    [Condition of type quicklisp-client:system-not-found]

Check ps-gadgets.asd find out depends-on **#:gadgets**
> ;;;; ps-gadgets.asd
> (asdf:defsystem #:ps-gadgets
>   :description "Describe ps-gadgets here"
>   :author "Your Name <your.name@example.com>"
>   :license "Specify license here"
>   :depends-on (#:parenscript
>                #:gadgets
>                #:alexandria)

How and Where can get :gadgets?

Thank you.

**Comment by BnMcGn** [comment]
You can clone gadgets from here:
https://github.com/BnMcGn/gadgets
